Gamedev
yousuf031991/HumanAgentInteraction pull request #30
Opened 2017-02-21 10:40 UTC by tgomudur

Moved gamepage functions into gamepageServices.js. Added room class to maintain room related data. Fixed issue #19

2017-02-21 20:10 UTC, yousuf031991 commented on MainApp/public/app/services/authServices.js
> +        };
Do we need both create and verify?

2017-02-24 00:54 UTC, yousuf031991 commented on MainApp/public/app/services/authServices.js
> +        };
What does this function do?

2017-02-24 03:13 UTC, super9user requested changes
Few review comments added. Please have a look and let me know if you want to discuss any of the comments.

2017-02-24 03:13 UTC, super9user commented on MainApp/public/app/services/authServices.js
> +        };
Yeah this seems to be a mistake of manual merge.
This method `create` is not required.

2017-02-24 03:13 UTC, super9user commented on MainApp/bower.json
> -     "angular-timer": "^1.3.4",
If there are no dependencies, can we get rid of bower.json?

2017-02-24 03:13 UTC, super9user commented on MainApp/lib/app/routes/api.js
> +import request from 'request';
Never used, Can we get rid of this?

2017-02-24 03:13 UTC, super9user commented on MainApp/package.json
> +    "request": "^2.79.0"
Same here, request is never used in app.

2017-02-24 03:13 UTC, super9user commented on MainApp/public/app/routes.js
> +    $routeProvider.when('/', {
Again, seems to be some mistake while resolving merge conflicts from master. 
Please fix. Look at the `routes.js` from the current master and update accordingly.

2017-02-24 03:13 UTC, super9user commented on MainApp/public/app/controllers/gamePageCtrl.js
> +        statsObject.username = "Syed";
Is this correct? I mean is the username always supposed to be "Syed" ?

2017-02-24 03:13 UTC, super9user commented on MainApp/lib/app/routes/api.js
> +            GameConfig.find({}, function(err, record) {
Shouldn't we pull the Current Active GameConfig? Instead of firing and empty find query

2017-02-24 03:13 UTC, super9user commented on MainApp/public/app/views/index.html
> +<html>
Merge conflict not resolved correctly here again.
Please remove this file.

2017-02-24 03:13 UTC, super9user commented on npm-debug.log
> +0 info it worked if it ends with ok
Lets not push `.log` files into github. Please remove

2017-02-24 04:08 UTC, tgomudur commented on MainApp/public/app/services/authServices.js
> +        };
Yeah. I think it was a mistake from manual merge

2017-02-24 04:09 UTC, tgomudur commented on MainApp/public/app/services/authServices.js
> +        };
I'll remove the create function.

2017-02-24 04:11 UTC, shahsyedzafar commented on MainApp/public/app/controllers/gamePageCtrl.js
> +        statsObject.username = "Syed";
No. It's just hard coded. We are in the process of writing a gameState function wherein you get the username along with score and resource count that writes in the userStatistics collection. Just for an end to end flow I hard coded. :)

2017-02-24 05:45 UTC, tgomudur commented on MainApp/bower.json
> -     "angular-timer": "^1.3.4",
Yeah. Removed it.

2017-02-24 05:45 UTC, tgomudur commented on MainApp/lib/app/routes/api.js
> +import request from 'request';
All unused packages have been removed with latest commit. Let me know if I missed any.

2017-02-24 05:46 UTC, tgomudur commented on MainApp/public/app/routes.js
> +    $routeProvider.when('/', {
Updated as per master branch

2017-02-24 05:46 UTC, tgomudur commented on MainApp/public/app/views/index.html
> +<html>
Removed index.html file.

2017-02-24 06:26 UTC, yousuf031991 commented on npm-debug.log
> +0 info it worked if it ends with ok
@tgomudur this one still remains unfixed

2017-02-24 06:56 UTC, shahsyedzafar commented on npm-debug.log
> +0 info it worked if it ends with ok
It was pushed by me. I will remove that.

2017-02-24 07:12 UTC, super9user approved these changes

2017-02-24 07:39 UTC, merged