Post game questionnaire
yousuf031991/HumanAgentInteraction pull request #46
Opened 2017-04-01 18:32 UTC by adityab17190

This pull request contains-
1) Fix for the radio button issue on lines 274 and 275 bin trustAndTaskQuestionnaire

2) Fix for the inconsistency issue observed when navigating from post game questionnaire to thank you page.

2017-04-02 02:53 UTC, super9user commented on MainApp/.gitignore
> -public/downloads/*
Why was this removed?

2017-04-02 02:54 UTC, super9user commented on MainApp/public/downloads/AdminLogs-1490230726013.csv
> +Logged At,Action,Author
Pls remove.

2017-04-02 02:54 UTC, super9user commented on MainApp/public/downloads/AdminLogs-1490229976070.csv
> +Logged At,Action,Author
Pls remove.

2017-04-02 02:54 UTC, super9user commented on MainApp/public/downloads/AdminLogs-1490228870888.csv
> +Logged At,Action,Author
Pls remove.

2017-04-02 02:55 UTC, super9user requested changes
A few comments.

2017-04-02 04:01 UTC, adityab17190 commented on MainApp/.gitignore
> -public/downloads/*
looks like the gamedev branch is 2 commits behind the master one of which contains the 'public/downloads/*' added to gitignore.

2017-04-02 04:06 UTC, adityab17190 commented on MainApp/.gitignore
> -public/downloads/*
@shahsyedzafar  and @tgomudur can you please look into this?

2017-04-02 04:12 UTC, yousuf031991 commented
Wait, why are gamedev commits in this PR?

2017-04-02 04:14 UTC, yousuf031991 commented on MainApp/.gitignore
> -public/downloads/*
Wait, why are gamedev commits from 10 days ago in this PR? These commits are already in master

2017-04-02 04:19 UTC, adityab17190 commented on MainApp/.gitignore
> -public/downloads/*
There was this bug occurring due to timeout function in gamePageCtrl.js not exiting. It was fixed by @shahsyedzafar  in this  commit https://github.com/yousuf031991/HumanAgentInteraction/pull/46/commits/7db7ceb3c386eda0000eee154522d4e61f1cf411.

2017-04-02 04:21 UTC, yousuf031991 commented on MainApp/.gitignore
> -public/downloads/*
@adityab17190 Maybe you should create a new branch from master and cherry pick your own commits into it.

2017-04-02 04:27 UTC, tgomudur commented on MainApp/.gitignore
> -public/downloads/*
I'm not sure why gamedev commits are showing here. But I'm removing the csvs and adding public/downloads/* to gitignore and committing.

2017-04-02 04:43 UTC, adityab17190 commented on MainApp/.gitignore
> -public/downloads/*
@tgomudur  and @super9user I have created new branch with following pull request #48

2017-04-11 21:35 UTC, adityab17190 commented
Duplicate

2017-04-11 21:35 UTC, closed without merging